services:
  admin-panel:
    image: ghcr.io/daniel-gia/raspberry-pi-chromium-kiosk-admin-panel:${IMAGE_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    network_mode: host

    environment:
      DATABASE_URL: file:/data/kiosk.db
      CHROME_REMOTE_URL: http://127.0.0.1:9222

      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

    volumes:
      - ./data:/data
